## --------------------------------------------------------------------
## AUTO GENERATED, DO NOT EDIT MANUALLY
##
## Generated by the GitHub Actions workflow:
##   `.github/workflows/submodule-export.yml`
##
## This file mirrors a read-only git submodule branch.
## Any local edits will be lost on regeneration.
## --------------------------------------------------------------------

class_name Network extends Node


func _init() -> void:
	hello_network("Network.init()")


static func hello_network(p_source: String) -> void:
	prints(p_source, "> Hello, Network!")
	Utils.hello_utils(p_source + " > Network")
